---
title: Data Scientist in Ads
author: Max Lin
date: '2018-07-10'
slug: data-scientist-in-ads
categories: []
tags: []
draft: no
---

BuzzFeed recently posted a job listing for [Data Scientist in Ads](https://www.buzzfeed.com/about/jobs?gh_jid=1237661) role. The job description begins with several adtech jargons:

> BuzzFeed is looking for a Data Scientist to join its growing team. The ideal candidate is passionate about business analytics, and has experience working in Ad-Tech, using Prebid, EBDA, and/or TAM data to optimize and strengthen programmatic advertising revenue streams. 

Those adtech jargons (Prebid, EBDA, TAM, programmatic advertising) can act as quick filters for candidates who do not have adtech exposure. BuzzFeed, after all, does require adtech experience for this data scientist role.  

> 2+ years of industry experience, working on data-related initiatives in adtech.

If you do not know what those jargons mean, you are less likely to apply for the job.

However, if we replace the jargons with more general economic terms,  it may attract a larger pool of candidates that do not have adtech domain knowledge but otherwise have similar data science skills:

> The ideal candidate is passionate about business analytics, and has experience using transaction data in Marketplace 1, Marketplace 2, and/or Marketplace 3 to increase revenue for the goods BuzzFeed produces.

[Prebid](http://prebid.org), [EBDA](https://support.google.com/dfp_premium/answer/7128958?hl=en), [TAM](https://aps.amazon.com/aps/transparent-ad-marketplace/index.html) are three marketplaces for selling advertising spaces that BuzzFeed produces. There will be more data science candidates that do not work at adtech but either work in a marketplace (e-commerce websites like [Etsy](https://www.etsy.com/) or [Ebay](https://www.ebay.com/)) or have experiences in selling merchanizes across multiple marketplaces. 

Disclaimer: I do not know anyone at BuzzFeed and do not have opinions about working at BuzzFeed.
